### ISSUE TITLE
Better handling of non-existing cog name

### ISSUE THREAD

**Issue by geirawsm** [geirawsm/sausage_bot#52]
```
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sausage_bot/util/cogs.py", line 227, in cog
    await action_on_cog(cmd_in, cog_names)
  File "/app/sausage_bot/util/cogs.py", line 191, in action_on_cog
    await Loading.load_cog(cog_name)
  File "/app/sausage_bot/util/cogs.py", line 60, in load_cog
    await config.bot.load_extension(
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1011, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'sausage_bot.cogs.youtbue' could not be loaded.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ExtensionNotFound: Extension 'sausage_bot.cogs.youtbue' could not be loaded.
```

**Comment by geirawsm** [comment]
Fixed in 5ea3c5705075def30330dfdddff7db1451ad6cf6
