### ISSUE TITLE
Error when running `/youtube list`

### ISSUE THREAD

**Issue by geirawsm** [geirawsm/sausage_bot#60]
```[ 17.06.2024 15.35.12 ] [ DATABASES ][ db_helper.get_output (658) ] /data/db/youtube_feeds.sqlite: Using this query: SELECT feed_name, url, channel FROM youtube_feeds ORDER BY feed_name ASC
2024-06-17 13:35:12 ERROR    discord.app_commands.tree Ignoring exception in command 'list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sausage_bot/cogs/youtube.py", line 205, in youtube_list
    for page in formatted_list:
TypeError: 'coroutine' object is not iterable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'list' raised an exception: TypeError: 'coroutine' object is not iterable```

**Comment by geirawsm** [comment]
Fixed in 538315df4e8b16c9440ee1e1d165a89888bd2e1c
